[package]
name = "txstr"
version = "0.1.0"
description = "decentralised, minimalist microblogging for hackers"
license = "MIT"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
dirs = "7.0.0"
ritualistic = "0.2.1"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "time"] }
toml = "1.1.6"
